  smtp:                                                                         
       username: 231f1126867a43                                                    
       # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
       # From mailtrap.io                                                          
       password: d16418f37c8a75
       host: smtp.mailtrap.io                                                      
       port: 2525                                                                  
       sender: admin@example.com 
